---
name: Maxwel
surname: Coura Oliveira
position: "Weed Scientist"
address: "São Paulo, SP"
phone: +55 31997268083
www: maxweeds.rbind.io
email: "maxwelco@tuta.com"
#twitter: maxwelco
github: maxwelco
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```



#  **Professional experiences**

## **Gaia Ciência Consultoria LTDA**

*Independent Consultant* · São Paulo · SP · Brazil \hfill Oct 2025 - Current

-   Provided data analysis services using R and Python, specializing in statistical modeling, data visualization, and reproducible research workflows.

-   Edited and revised academic manuscripts, grant proposals, and technical reports for clarity, structure, and impact; experienced with journal-specific styles.

-   Collaborated with researchers and organizations to develop polished deliverables under tight deadlines, improving publication acceptance and funding success rates.

-   Advised graduate students and early-career researchers on research design, academic writing, and data presentation.

## **BASF Digital Farming**

*Senior Research & Digital Agronomist* · Cologne · NRW · Germany \hfill Oct 2023 - Sep 2025

-   Coordinated smart spraying research and development for the **One Smart Spray** platform in the US, enhancing precision farming capabilities.

-   Built and maintained strong stakeholder relationships, fostering collaboration across global teams.

-   Developing digital agronomic intelligence and sustainability algorithms for decision-making in crop protection stewardship.

-   Agronomic coordinator of *Expert Scouting Trip* (field monitoring) project based on modeling and remote sensing of the **xarvio AgBusiness** platform.


## **McGill University**

*Assistant Professor of Weed Science* · Saint-Anne-de-Bellevue · QC · Canada \hfill Dec 2022 - Sep 2023

-   Tenure-track research and teaching in Crop Protection --Weed Science.

-   Delivered agronomic research and grower engagement to advance sustainable vegetable production using integrated pest and weed management approaches.


## **TeeJet Technologies South America**

*Research and Training Coordinator* · Sao Paulo · SP · Brazil \hfill Nov 2021 - Oct 2022

-   Developed strategies for nozzle positioning in pesticide application, and maintained relationships with stakeholders.

-   Led certified applicator training to minimize environmental impact and enhance regenerative herbicide stewardship in soybean and corn systems.


## **Western São Paulo University**

*Assistant Professor* · Presidente Prudente · SP · Brazil \hfill Fev 2020 - Fev 2021

-   Taught courses and workshops on weed biology, agronomy, and programming in R.

-   Conducted surveys and research on sustainable weed management practices, integrating precision herbicide programs to enhance resilience and soil health in family farm cotton production systems.

## **University of Wisconsin-Madison**

*Research Associate/Data analyst*, [WiscWeeds Lab](http://www.wiscweeds.info/) · Remote \hfill Jan 2020 - Sep 2021

-   Analyzed complex datasets with empirical and machine learning models, and published manuscripts in high-impact journals.

-   Mentored graduate students in experimental design, writing and data visualization techniques for effectively communicating research findings.

*Postdoctoral Research Associate*, [WiscWeeds Lab](http://www.wiscweeds.info/) · Madison · WI · USA \hfill Jan 2018 - Dec 2019

-   Developed integrated weed management strategies for corn and soybeans in Wisconsin, USA

-   Led herbicide resistance studies and field herbicide efficacy trials with chemical industry.

-   Conducted research on off-target herbicide movement (e.g., 2,4-D and dicamba) that was used by [EPA](https://www.epa.gov/) product registration decision.

-   Delivered extension talks and outreach activities to stakeholders and growers.

-   Supported students’ academic growth and contributed to grant proposals and publications.


## **University of Nebraska-Lincoln**

*Graduate Research Assistant*, [Knezevic Lab](https://agronomy.unl.edu/knezevic) · Concord/Lincoln · NE · USA \hfill Jan 2014 to Dec 2017

-   Conducted field (corn and soybeans), greenhouse, and laboratory research on herbicide resistance, toxicology and weed ecology.

-   Designed and executed extension talks on integrated weed management and conducted herbicide efficacy trials with chemical industry.


## **TIMAC Agro Brasil**

*Sales Management Trainee*, Paragominas · PA · Brazil \hfill Jan to Jun 2013

-   Conducted sales prospecting and marketing campaigns to expand client base.

-   Organized and delivered training sessions to enhance team performance and product knowledge.



#  **Education**

**Ph.D. in Agronomy (Weed Science)** · University of Nebraska-Lincoln \hfill Jan 2014 to Dec 2017\
*Dissertation*: Evolution of HPPD-inhibitor herbicide resistance in a waterhemp (*Amaranthus tuberculatus* var. *rudis*) population from Nebraska, USA\
*Advisor*: Dr. Stevan Knezevic | *Co-advisor*: Dr. Todd Gaines, Dr. Amit Jhala

**MSc. in Plant Science (Weed Science)** · Federal University of Jequitinhonha and Mucuri Valleys \hfill Ago 2011 to Jul 2013\
*Thesis*: Competitive ability of corn with *Commelina benghalensis* and *Richardia brasiliensis*\
Advisor: Dr. José B Santos

**BSc. in Agronomy** · Federal University of Jequitinhonha and Mucuri Valleys \hfill Mar 2006 to Jul 2011\
*Thesis*: Composition and extraction of minerals in forage grass in a previously soil waste urban deposit area\
*Advisor*: Dr. Karina G. Ribeiro


#  **Technical qualifications and skills**

## **Technical Expertise**

-  *Laboratory*: Experience on liquid and gas chromatography mass spectrometry (LC- and GC-MS), spectrophotometer, gene sequencing, expression, and molecular markers

-   *Field/Greenhouse*:   Digital agriculture, Agronomic crops, experiment setup and design, resistance screening, grading, dose response, herbicide efficacy, herbicide selectivity, crop safety, herbicide dissipation in the soil, carryover, herbicide synergism, integrated weed management, and cover crops


## **Data analysis/modeling**

-   Skills in data analysis using different packages from R and Rstudio software: blog, presentations, reports, books, manuscripts, data visualization, maps, ANOVA, linear and non-linear models, mixed models, machine learning, and others. Advance skills in Python, LaTeX, Quarto, Markdown, GitHub, Confluence, Jira. Also, intermediate skills in SAS, Terminal, and CSS.


## **Languages**

-   *Portuguese*: Native proficiency (reading, writing, and speaking).

-   *English*: Fluent proficiency (reading, writing, and speaking).

-   *Spanish*: Intermediate proficiency (reading and conversational speaking, listening).

-   *Italian*: Intermediate proficiency (reading, conversational speaking, listening).

-   *French*: Basic proficiency (reading, listening).

-   *German*: Basic proficiency (reading, basic speaking).


#  **Selected peer-reviewed publications**

1.  **Oliveira MC**, da Silva AL, Ulguim AR, and Werle R (2021) Assessment of weed management strategies and challenges in Brazilian cropping systems. *Weed Technology* 35:155-165 doi: [10.1017/wet.2020.96](https://doi.org/10.1017/wet.2020.96)

1. **Oliveira MC**, Jhala AJ, Bernards ML, Proctor CA, Stepanovic S, Werle R (2022) Palmer Amaranth (*Amaranthus palmeri*) Adaptation to US Midwest Agroecosystems. *Frontiers in Agronomy* 4, doi: [10.3389/fagro.2022.887629]( https://doi.org/10.3389/fagro.2022.887629)

1. **Oliveira MC**, Gaines TA, Dayan FE, Patterson EL, Jhala AJ, and Knezevic SZ (2018) Reversing resistance to tembotrione in an *Amaranthus tuberculatus* (syn. *rudis*) population from Nebraska, USA with cytochrome P450 inhibitors. *Pest Management Science*, 74:2296--2305. (Invited publication) doi: [10.1002/ps.4697](https://onlinelibrary.wiley.com/doi/full/10.1002/ps.4697)

1. **Oliveira MC**, Jhala A, Gaines T, Irmak S, Amundsen K, Scott JE, and Knezevic SZ (2017) Confirmation and control of HPPD-inhibiting herbicide-resistant waterhemp (*Amaranthus tuberculatus*) in Nebraska. *Weed Technology*, 31:67--79. doi: [10.1017/wet.2016.4](https://www.cambridge.org/core/journals/weed-technology/article/confirmation-and-control-of-hppdinhibiting-herbicideresistant-waterhemp-amaranthus-tuberculatus-in-nebraska/69C31C7039DBE3FD49A55C73EEE5F2EE)


A complete list of publications is available upon request or can be accessed on [Maxwel Coura Oliveira - Google Scholar](https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=nwwARKUAAAAJ&sortby=pubdate)


#  **Certification**

1.   Teaching and [tidyverse instructor certification](https://education.rstudio.com/trainers/people/oliveira+maxwel/) \hfill February 2021\
    Issue by [Rstudio](https://rstudio.com/)

1. Pesticide applicator license \hfill March 2018\
    Issue by Wisconsin Department of Agriculture










