---
name: Maxwel
surname: Coura Oliveira
position: "Research agronomist"
address: "Cologne, Germany"
phone: +49 15205854941
www: maxweeds.rbind.io
email: "maxwelco@tuta.com"
#twitter: maxwelco
github: maxwelco
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

#  Summary

Agricultural scientist with a strong background in crop protection, digital farming, and market-relevant research across academic, industry, and regulatory environments. Proven track record in delivering actionable insights from complex datasets through advanced analytics, including statistical modeling, machine learning, and data visualization in R and Python. Experienced in managing field trials, synthesizing secondary data, and producing high-impact reports for diverse stakeholders. Author of 30+ peer-reviewed publications and recognized internationally for bridging agronomic research with practical, data-driven decision-making. Fluent in English, Portuguese, and Spanish, with cross-continental expertise spanning Latin America, North America, and Europe.



# Professional experiences

## **BASF Digital Farming**

*Senior Digital Agronomist* · Cologne · NRW · Germany \hfill Oct 2023 - Current

-   Coordinated smart spraying research and development for the **One Smart Spray** platform in the US, enhancing precision farming capabilities.

-   Built and maintained strong stakeholder relationships, fostering collaboration across global teams.

-   Developing agronomic digital intelligence for **One Smart Spray** and **xarvio Field Manager**.

-   Agronomic coordinator of *Expert Scouting Trip* (field monitoring) project based on modeling and remote sensing of the **xarvio AgBusiness** platform.


## **McGill University**

*Assistant Professor of Weed Science* · Saint-Anne-de-Bellevue · QC · Canada \hfill Dec 2022 - Sep 2023

-   Tenure-track research and teaching in Weed Science.

-   Led agronomic research projects on sweet corn with [Groupe Bonduelle](https://www.bonduelle.com/fr/) and delivered extension talks to stakeholders.


## **TeeJet Technologies South America**

*Research and Training Coordinator* · Sao Paulo · SP · Brazil \hfill Nov 2021 - Oct 2022

-   Developed strategies for nozzle positioning in pesticide application, and maintained relationships with stakeholders.

-   Led certified training programs for pesticide applicators on auxin herbicide (e.g., 2,4-D, dicamba) application in field crops. 


## **Western São Paulo University**

*Assistant Professor* · Presidente Prudente · SP · Brazil \hfill Fev 2020 - Fev 2021

-   Taught courses and workshops on weed biology, agronomy, and programming in R.

-   Conducted surveys and research on herbicide weed management and cover crop strategies in corn and soybean farming systems.

## **University of Wisconsin-Madison**

*Research Associate/Data analyst*, [WiscWeeds Lab](http://www.wiscweeds.info/) · Remote \hfill Jan 2020 - Sep 2021

-   Analyzed complex datasets with empirical and machine learning models, and published manuscripts in high-impact journals.

-   Mentored graduate students in experimental design, writing and data visualization techniques for effectively communicating research findings.

*Postdoctoral Research Associate*, [WiscWeeds Lab](http://www.wiscweeds.info/) · Madison · WI · USA \hfill Jan 2018 - Dec 2019

-   Developed integrated weed management strategies for corn and soybeans in Wisconsin, USA

-   Led herbicide resistance studies and field herbicide efficacy trials with chemical industry.

-   Conducted research on off-target herbicide movement (e.g., 2,4-D and dicamba) that was used by [EPA](https://www.epa.gov/) product registration decision.

-   Delivered extension talks and outreach activities to stakeholders and growers.

-   Supported students’ academic growth and contributed to grant proposals and publications.


## **University of Nebraska-Lincoln**

*Graduate Research Assistant*, [Knezevic Lab](https://agronomy.unl.edu/knezevic) · Concord/Lincoln · NE · USA \hfill Jan 2014 to Dec 2017

-   Conducted field (corn and soybeans), greenhouse, and laboratory research on herbicide resistance, toxicology and weed ecology.

-   Designed and executed extension talks on integrated weed management and conducted herbicide efficacy trials with chemical industry.


## **TIMAC Agro Brasil**

*Sales Management Trainee*, Paragominas · PA · Brazil \hfill Jan to Jun 2013

-   Conducted sales prospecting and marketing campaigns to expand client base.

-   Organized and delivered training sessions to enhance team performance and product knowledge.



# Education

**Ph.D. in Agronomy (Weed Science)** · University of Nebraska-Lincoln \hfill Jan 2014 to Dec 2017\
*Dissertation*: Evolution of HPPD-inhibitor herbicide resistance in a waterhemp (*Amaranthus tuberculatus* var. *rudis*) population from Nebraska, USA\
*Advisor*: Dr. Stevan Knezevic | *Co-advisor*: Dr. Todd Gaines, Dr. Amit Jhala

**MSc. in Plant Science (Weed Science)** · Federal University of Jequitinhonha and Mucuri Valleys \hfill Ago 2011 to Jul 2013\
*Thesis*: Competitive ability of corn with *Commelina benghalensis* and *Richardia brasiliensis*\
Advisor: Dr. José B Santos

**BSc. in Agronomy** · Federal University of Jequitinhonha and Mucuri Valleys \hfill Mar 2006 to Jul 2011\
*Thesis*: Composition and extraction of minerals in forage grass in a previously soil waste urban deposit area\
*Advisor*: Dr. Karina G. Ribeiro


# Languages

-   *English*: Fluent proficiency (reading, writing, and speaking).

-   *Portuguese*: Native → Key for Brazilian leaf operations

-   *Spanish*: Professional → Latin American supply chains

-   *Italian*: Intermediate proficiency (reading, conversational speaking, listening).

-   *French*: Basic proficiency (reading, listening).

-   *German*: Basic proficiency (reading, basic speaking).

#  Selected peer-reviewed publications

## **Herbicide weed resistance**

1. **Oliveira MC**, Jhala A, Gaines T, Irmak S, Amundsen K, Scott JE, and Knezevic SZ (2017) Confirmation and Control of HPPD-inhibiting Herbicide-Resistant Waterhemp (*Amaranthus tuberculatus*) in Nebraska. *Weed Technology*, 31:67--79. doi: [10.1017/wet.2016.4](https://www.cambridge.org/core/journals/weed-technology/article/confirmation-and-control-of-hppdinhibiting-herbicideresistant-waterhemp-amaranthus-tuberculatus-in-nebraska/69C31C7039DBE3FD49A55C73EEE5F2EE)

1. **Oliveira MC**, Gaines TA, Dayan FE, Patterson EL, Jhala AJ, and Knezevic SZ (2018) Reversing resistance to tembotrione in an *Amaranthus tuberculatus* (syn. *rudis*) population from Nebraska, USA with cytochrome P450 inhibitors. *Pest Management Science*, 74:2296--2305. (Invited publication) doi: [10.1002/ps.4697](https://onlinelibrary.wiley.com/doi/full/10.1002/ps.4697)


## **Herbicide weed management**

1.  **Oliveira MC**, Osipitan OA, Begcy K, and Werle R (2020) Cover crops, hormones and herbicides: priming an integrated weed management Strategy. *Plant Science* 301:110550 doi: [10.1016/j.plantsci.2020.110550](https://doi.org/10.1016/j.plantsci.2020.110550)

1.  Knezevic SZ, Pavlovic P, Barnes ER, Beiermann C, **Oliveira MC**, Lawrence N, Scott JE, and Jhala AJ (2019) Critical Time for Weed Removal in Glyphosate-Resistant Soybean as Influenced by Preemergence Herbicides. 33:393-399. *Weed Technology*. doi: [10.1017/wet.2019.18](https://doi.org/10.1017/wet.2019.18)

1.  Soltani S, **Oliveira MC**, Alves GS, Werle R, Norsworthy JK, Sprague CL, Young BG, Reynolds DB, Brown A, and Sikkema PH (2020) Off-Target Movement Assessment of Dicamba in North America. *Weed Technology* 34:318-330. doi: [10.1017/wet.2020.17](https://doi.org/10.1017/wet.2020.17)

## **Weed ecology**

1. **Oliveira MC**, Jhala AJ, Bernards ML, Proctor CA, Stepanovic S, Werle R (2022) Palmer Amaranth (*Amaranthus palmeri*) Adaptation to US Midwest Agroecosystems. *Frontiers in Agronomy* 4, doi: [10.3389/fagro.2022.887629]( https://doi.org/10.3389/fagro.2022.887629)

1. Mobli A, **Oliveira MC**, Butts L, Proctor C, Lawrence N, Werle R (2022) Emergence pattern of horseweed (*Erigeron canadensis* L.) accessions across Nebraska. *Weed Technology* 36:655-662 doi: [10.1017/wet.2022.62](https://doi.org/10.1017/wet.2022.62)

## **Agronomic crops** 

1. Grint K, Arneson NJ, Arriaga F, DeWerff R, **Oliveira M**, Smith DH, Stoltenberg DE, Werle R (2022) Cover crops and preemergence herbicides: an integrated approach for weed management in corn-soybean systems in the US Midwest. *Frontiers in Agronomy* 4:888349 [10.3389/fagro.2022.888349](https://doi.org/10.3389/fagro.2022.888349)

1. Ortmeier‐Clarke HJ, Laboski CAM, **Oliveira MC**, Arneson NJ, Conley SP, Werle R (2023) Cultivar and management effects on industrial hemp yields in Wisconsin. Agronomy Journal 115:1335-1343 doi: [10.1002/agj2.21297](https://doi.org/10.1002/agj2.21297)

## **Surveys**

1.  **Oliveira MC**, da Silva AL, Ulguim AR, and Werle R (2021) Assessment of weed management strategies and challenges in Brazilian cropping systems. *Weed Technology* 32:754-761 doi: [10.1017/wet.2020.96](https://doi.org/10.1017/wet.2020.96)

1. **Oliveira MC**, Butts, L, and Werle R, (2018) Assessment of cover crop management strategies in Nebraska, US. *Agriculture* 6:754-761 doi: [10.3390/agriculture9060124](https://doi.org/10.3390/agriculture9060124)


A complete list of publications is available upon request or can be accessed on [Maxwel Coura Oliveia - Google Scholar](https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=nwwARKUAAAAJ&sortby=pubdate)

#  Technical bulletins and extension articles

1. Striegel S, **Oliveira MC**, Arneson NJ, Conley SP, Stoltenberg DE, and Werle R (2020) Spray solution pH as influenced by synthetic auxin formulation and spray additives. *WiscWeeds* Link: [link](https://www.wiscweeds.info)

1. Striegel S, **Oliveira MC**, Arneson NJ, Conley SP, Stoltenberg DE, and Werle R (2020) Soybean injury as influenced by synthetic auxin
formulation and spray additives. *WiscWeeds* Link: [link](https://www.wiscweeds.info)


1.  Alves DP, Reis MR, Pereira GAM, Silva MMJ, Nascimento MA, and **Oliveira MC** (2020) Injúrias causadas por residual de herbicidas na cultura do alho. *Universidade Federal de Viçosa* [Link](https://boletimagrotecnico.crp.ufv.br/?wpdmpro=boletim-03-injurias-causadas-por-residual-de-herbicidas-na-cultura-do-alho)

1.  Gomes CA, Reis MR, Silva MMJ, Pereira GAM, and **Oliveira MC** (2020) Injúrias causadas por residual de herbicidas na cultura da cebola. *Universidade Federal de Viçosa* [Link](https://boletimagrotecnico.crp.ufv.br/?wpdmpro=boletim-02-injurias-causadas-por-residual-de-herbicidas-na-cultura-da-cebola)

1.  **Oliveira MC**, Pereira GAM, Takano H, Nunes AL, and Reis MR (2020) Classificação dos herbicidas no Brasil. *maxweeds* [Link](https://maxweeds.rbind.io/post/chart/Chart_Herbicida.pdf)

1.  Arneson NJ, Smith DH, DeWerff R, **Oliveira MC, and** Rodrigo Werle (2019) Residual control of waterhemp with pre-emergence herbicides in soybean. *WiscWeeds* [Link](https://www.wiscweeds.info)

1.  Smith DH, Broeske M, Patton J, Shelley K, Arriaga F, Jensen B, **Oliveira MC,** Briski B, Bubolz B, Rushmann R, Johnson H, Schriefer G, and Sorge M (2019) Cover Crops 101. *University of Wisconsin-Madison* [Link](https://learningstore.extension.wisc.edu/collections/farming/products/cover-crops-101)

1.  **Oliveira MC** and Werle R (2018) Herbicide site of action key for crop injury symptoms. *WiscWeeds* Link: [EN](https://maxweeds.rbind.io/files/2018_HerbicideInjury_EN.pdf) and [PT](https://maxweeds.rbind.io/files/2018_HerbicideInjury_BRA.pdf).

# Certification

1.   Teaching and [tidyverse instructor certification](https://education.rstudio.com/trainers/people/oliveira+maxwel/) \hfill February 2021\
    Issue by [Rstudio](https://rstudio.com/)

1. Pesticide applicator license \hfill March 2018\
    Issue by Wisconsin Department of Agriculture




