---
output: 
  pdf_document: 
    latex_engine: pdflatex
    template: ~/Dropbox/CV/CV_TEST.tex
geometry: margin=1in 

title: "Curriculum Vitae"
author: "Maxwel Coura Oliveira, PhD" 

jobtitle: "Pesquisador Associado, Universidade de Wisconsin-Madison"
address: "1575 Linden Drive · Departamento de Agronomia · Madison, Wisconsin, EUA 53706"
fontawesome: yes
email: max.oliveira@wisc.edu
github: maxwelco
twitter: dr_olives1
phone: "+1 402 580 6652"
web: maxweeds.rbind.io
#updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---


# EDUCAÇÃO

• *Universidade de Nebraska-Lincoln*, Ph.D. Agronomia (Planta daninha) \hfill Dez 2017


• *Universidade Federal dos Vales do Jequitinhonha e Mucuri*, MSc. Produção vegetal (Planta daninha) \hfill Jul 2013


• *Universidade Federal dos Vales do Jequitinhonha e Mucuri*, BSc. Agronomia \hfill Jul 2011                



# EXPERIÊNCIA PROFISSIONAL

• *Pesquisador Associado*, [WiscWeeds Lab](http://www.wiscweeds.info/) · Universidade de Wisconsin-Madison · 
Madison · WI · EUA Jan 2018       
*Objetivo*: realizar pesquisa inovadora e colaborativa e de extensão em biologia, ecologia e manejo de ervas daninhas problemáticas em milho, soja e cânhamo sob a supervisão do Dr. Rodrigo Werle. Responsável pelas análises de dados dos experimentos de laboratório e campo, escrita de artigos científicos, relatórios e liderar os estudantes de mestrado nos experimentos e análises de dados. Parte do time de implementação, condução, coleta e análise de dados dos ensaios de herbicidas de empresas de herbicidas. Fui responsável pelo [website](http://www.wiscweeds.info/) do laboratório.

• *Doutoramento*, [Knezevic Lab](https://agronomy.unl.edu/knezevic) Universidade de Nebraska-Lincoln, Lincoln · NE · EUA  \hfil Jan, 2014 to Dez 2017            
*Objetivo*: Pesquisa de doutorado em Sistemas de Produção, Biologia e Ecologia de Plantas Daninhas, Manejo Integrado de Plantas Daninhas, Evolução da Resistência a Herbicidas e ensaios de eficácia de herbicidas sob a supervisão do Dr. Stevan Knezevic. Parte do time de implementação, condução, coleta e análise de dados dos ensaios de herbicidas de empresas de herbicidas.

• *Trainee*, [TIMAC Agro](http://www.timacagro.com.br/) · Paragominas · PA · Brasil \hfill Jan to Jun 2013  
*Objetivo*: Treinado para ser um supervisor de equipe de vendas de fertilizantes, aquisição de talentos e marketing

• *Mestrado*, [Universidade Federal dos Vales do Jequitinhonha e Mucuri](http://www.ufvjm.edu.br/) · Diamantina · MG · Brasil \hfill Jul 2011 to Dez 2012  
*Objetivo*: Mestrado em biologia, competição e manejo integrado de ervas daninhas sob supervisão do Dr. José Barbosa dos Santos

• *Estágio internacional*, [The Ohio Program](https://top.osu.edu/) · OH · EUA 
\hfill Abr 2010 to Mar 2011  
*Objetivo*: Mão de fazenda em uma fazenda de vegetais em Michigan (EUA) e assistente em uma estufa de tomate hidropônico em Nova York, EUA

• *Estágio*, Pulveriza Fertilizers · Matipó · MG · Brasil \hfill Jul 2009  
*Objetivo*: trabalho em uma industria de fertilizantes foliares para milho, soja e café

• *Coordenador*, [CREA Jr](https://junior.creadf.org.br/) · Diamantina · MG · Brasil \hfill Jan to Dez 2009  
*Objetivo*: Liderar o clube para estudantes, conectar estudantes a engenheiros profissionais, organizar seminários, atrair novos membros

• *Estágio*, [EMATER MG](http://www.emater.mg.gov.br/) · Santana do Paraíso · MG · Brasil \hfill Jul 2008  
*Objetivo*: trabalho de extensão com pequenos produtores rurais

# ENSINO

• *Universidade de Wisconsin-Madison*, Peparação para o Camp de Herbologia \hfill Primavera 2018


• *Universidade de Nebraska-Lincoln*, Lab de Plantas Invasoras \hfill Primavera 2016/2017 


• *Universidade Federal dos Vales do Jequitinhonha e Mucuri*, Lab de Plantas Daninhas \hfill Primavera 2011


• *Universidade Federal dos Vales do Jequitinhonha e Mucuri*, Lab de Melhoramento Genético \hfill Primavera/Outono 2009


# PESQUISADOR VISITANTE

• *Universidade de Illinois Urbana-Champaign* · IL · EUA \hfill Set 2017  
Pesquisa sobre mecanísmo de resistência de *Amaranthus palmeri* para herbicidas inibidores da PPO sob supervisão de Dr. Pat Tranel


• *Universidade do Estado do Colorado–Fort Collins* · CO · EUA \hfill Mai 2017  
Pesquisa no lab sobre resistencia de *Amaranthus tuberculatus* aos herbicidas inibidores da HPPD sob supervisão de Dr. Todd Gaines


• *Universidade do Estado do Colorado–Fort Collins* · CO · EUA \hfill Set 2016  
Pesquisa no lab sobre fisiologia dos hebricidas inibidores da HPPD em *Amaranthus tuberculatus* sob supervisão de Dr. Franck Dayan


• *Universidade Federal de Viçosa-Viçosa* · MG · Brasil \hfill Ago 2012 à Dez 2012   
Pesquisa no campo, lab e estufas com comportamento de herbicidas no solo e manejo de plantas daninhas sob supervisão do Dr. Antonio Alberto Silva

# HONRAS ACADÊMICAS E PRÊMIOS

• *Congresso da North Central Weed Science Society*, Saint louis · MO · EUA \hfill Dez 2017  
Melhor Apresentação de Poster (Resistência de Plantas Daninhas)


• *Competição da North Central Weed Science Society*, Ames · IA  · EUA \hfill Jul 2017  
Primeiro Colocado Time e Primeiro Colocado Individual em Identificação de Herbicidas


• *Universidade de Nebraska-Lincoln*, Lincoln · NE · EUA \hfill Mar 2017  
Travel Grant ($400) to attend the 2017 Global Herbicide Resistant Conference


• *Campeonato de Herbologia da North Central Weed Science Society*, West Laffayete · EUA \hfill Jul 2016  
Terceiro Colocado Time 


• *Congresso da Weed Science Society of America*, San Juan · PR \hfill Fev 2015  
Primeiro Colocado Poster (Biologia de Plantas Daninhas)


• *Campeonato de Herbologia da Western Weed Science Society*, Columbus · OH · EUA \hfill Jul 2015  
Terceiro Colocado Time e Terceiro Colocado individual


• *Instituto Educacional Mayrink Vieira*, Ipatinga · MG · BRA \hfill Set 2002  
Melhor projeto (Pilhas e Eletrólise) da feira de ciências


• *Instituto Educacional Mayrink Vieira*, Ipatinga · MG · BRA \hfill Set 2001  
Melhor projeto (Organelas Celulares) da feira de ciências


# MEMBRO DE SOCIEDADES PROFISSIONAIS

• Weed Science Society of America

• North Central Weed Science Society

# MANUSCRITOS EM PREPARAÇÃO 

• Soltani N, **Oliveira MC**, Alves G, Werle R, Kruger G, Norsworthy J, Sprague C, Young B, Reynolds D, and Sikkema P (2019) Large-Scale Off-Target Movement Assessment of Dicamba in North America. Target Journal: *Weed Technology*

# PRINCIPAIS PUBLICAÇÕES

• **Oliveira MC**, Butts L, and Werle R (2019) Survey of cover crop management in Nebraska. 9:1-14 *Agriculture*, invited submission for special issue entitled: “Cover Crops”. doi: [10.3390/agriculture9060124](https://doi.org/10.3390/agriculture9060124)

• Knezevic SZ, Pavlovic P, Barnes ER, Beiermann C, **Oliveira MC**, Lawrence N, Scott JE, and Jhala AJ (2019) Critical Time for Weed Removal in Glyphosate-Resistant Soybean as Influenced by Preemergence Herbicides. 33-393:399. *Weed Technology*. doi: [10.1017/wet.2019.18](https://doi.org/10.1017/wet.2019.18)

• Werle R, **Oliveira MC**, Jhala AJ, Klein R, Proctor CA, and Rees J (2018) Survey of Nebraska farmers’
adoption of dicamba-tolerant soybean technology and off-target movement. *Weed
Technology*, 32:754--761. doi: [10.1017/wet.2018.62](https://doi.org/10.1017/wet.2018.62)

• **Oliveira MC**, Gaines TA, Patterson EP, Jhala AJ, Irmak S, Amundsen K, and Knezevic SZ (2018)
Interspecific and intraspecific transfer of metabolism based mesotrione resistance transfer
in dioecious weedy *Amaranthus*. *Plant Journal*. 96:1051--1063. doi: [10.1111/tpj.14089](https://onlinelibrary.wiley.com/doi/full/10.1111/tpj.14089)


• Knezevic SZ, Ospitan AO, **Oliveira MC**, and Scott JE (2018) *Lythrum salicaria* (purple loosestrife) control with herbicides: multiyear applications. *Invasive Plant Science and Management*. 11:143--154. doi: [10.1017/inp.2018.17](https://doi.org/10.1017/inp.2018.17)

• **Oliveira MC**, Pereira GAM, Ferreira EA, Barbosa JB, Knezevic SZ, and Werle R (2018) Additive
design: the concept and data analysis. *Weed Research*, 58:338--347. doi: [10.1111/wre.12317](https://onlinelibrary.wiley.com/doi/full/10.1111/wre.12317)


• **Oliveira MC**, Gaines TA, Jhala AJ, and Knezevic SZ (2018) Inheritance of mesotrione
resistance in an (*Amaranthus tuberculatus*) (var. *rudis*) population from Nebraska, EUA.
*Frontiers in Plant Science*, 9:60. doi: [10.3389/fpls.2018.00060](https://www.frontiersin.org/articles/10.3389/fpls.2018.00060/full)


• Miller JJ, Schepers JS, Shapiro CA, Arnenson NJ, Eskridge KM, **Oliveira MC**, and Giesler LJ
(2018) Characterizing soybean vigor and productivity using multiple crop canopy sensor
readings. *Field Crops Research*, 216:22--31. doi: [10.1016/j.fcr.2017.11.006](https://www.sciencedirect.com/science/article/pii/S0378429017310341)


• **Oliveira MC**, Gaines TA, Dayan FE, Patterson EL, Jhala AJ, and Knezevic SZ (2018)
Reversing resistance to tembotrione in an *Amaranthus tuberculatus* (syn. *rudis*)
population from Nebraska, EUA with cytochrome P450 inhibitors. *Pest Management
Science*, 74:2296--2305. (Publicação convidado) doi: [10.1002/ps.4697](https://onlinelibrary.wiley.com/doi/full/10.1002/ps.4697)


• **Oliveira MC**, Feist D, Eskelsen S, Scott JE, and Knezevic SZ (2017) Weed control in soybean with
preemergence and postemergence-applied herbicides. *Crop, Forage, and Turfgrass
Management*, 3:1--7


• **Oliveira MC**, Jhala A, Gaines T, Irmak S, Amundsen K, Scott JE, and Knezevic SZ (2017)
Confirmation and Control of HPPD-inhibiting Herbicide-Resistant Waterhemp
(*Amaranthus tuberculatus*) in Nebraska. *Weed Technology*, 31:67--79. doi: 
[10.1017/wet.2016.4](https://www.cambridge.org/core/journals/weed-technology/article/confirmation-and-control-of-hppdinhibiting-herbicideresistant-waterhemp-amaranthus-tuberculatus-in-nebraska/69C31C7039DBE3FD49A55C73EEE5F2EE)


•  Butts TR, Miller JJ, Pruitt JD, Vieira BC, **Oliveira MC**, Ramirez II S, and Lindquist JL (2017)
Light quality effect on corn growth as influenced by weed species and nitrogen
rate. *Journal of Agricultural Science*, 9:15--27. doi: [10.5539/jas.v9n1p15](http://www.ccsenet.org/journal/index.php/jas/article/view/63437)


• Braga RR, Santos JB, Zanuncio JC, Bibiano CS, Ferreira EA, **Oliveira MC**, Silva DV, and Serrāo JE
(2016) Effect of growing *Brachiaria brizantha* on phytoremediation of picloram under
different pH environments. *Ecological Engineering*, 94:102--106. doi: [10.1016/j.ecoleng.2016.05.050](https://www.sciencedirect.com/science/article/pii/S0925857416302853)

# PALESTRAS E TREINAMENTOS

• *Valoriza Agronegocios*, Patos de Minas · MG · Brasil \hfill Jan 2019  
Título: “Treinamento resistência, dicamba, identificação de plantas daninhas e herbicidas”

• *II IMAST*, Dracena · SP · Brasil \hfill Set 2018  
Título: “Da resistência ao dicamba: o desafio no manejo de plantas daninhas nos EUA”

• *JF Crow Institute for the Study of Evolution*, Madison · WI · EUA \hfill Set 2018  
Título: Evolução de *Amaranthus tuberculatus* aos herbicidas inibidores da 4-hydroxyphepylpiruvate dioxygenase


# EXTENSÃO

• Evolução de Resistência em *Amaranthus tuberculatus*.  
*Waterhemp worshop*, Chippewa Falls, Bangor, Janesville, Appleton, WI, EUA, Mar 2019

• Dia de Campo de Agronomia.  
*Wisconsin Cropping Systems Weed Science Field Day*, Arlington, WI, EUA, Jul 2018

• Dia de Campo da Mandioca, Diamantina, MG, Brasil, Out 2011

# ORGANIZAÇÃO DE EVENTOS

• Dia de Campo de Planta Daninha, Arlington and Lancaster · WI · EUA \hfill Jul 2018

• *Flaming Weed Control Workshop*, Concord · NE · EUA \hfill Ago 2014/15/16/17

• Dia de Campo da Mandioca, Diamantina, MG, Brasil \hfill Out 2011

• II Seminário das Pastagens, Diamantina · MG · Brasil \hfill Mar 2009

• I Seminário das Engenharias, Diamantina · MG · Brasil \hfill Set 2009


# PROJETOS APROVADOS

• [UW-Madison Division of Extension and UW-Madison CALS](https://oeo.cals.wisc.edu) \hfill Mar 2019 *Adaptation of Industrial Hemp (Cannabis sativa) to Agronomic practices in Wisconsin*
Valor: $35000

• [Wisconsin Corn Promotion Board](http://wicorn.org) \hfill Jan 2019  
*Weed Management Challenges in Wisconsin Corn Production* 
Valor: $30000

• Fundação [CAPES](http://www.capes.gov.br/) \hfill Set 2013  
Evolução de *Amaranthus tuberculatus* aos herbicidas inibidores da 4-hydroxyphepylpiruvate dioxygenase em Nebraska  
Valor $130000

# MANUAIS

• *Cover Crops* 101 \hfill Agosto 2019   
[Link](https://learningstore.extension.wisc.edu/collections/farming/products/cover-crops-101)

• Manual de Identificação de Injúrias em Culturas Causadas por Herbicidas \hfill Set 2018  
[Inglês](http://www.wiscweeds.info/img/2018%20Herbicide%20SOA%20injury%20chart/2018_HerbicideInjury_EN.pdf) and [Português](https://maxweeds.rbind.io/files/Herbicide%20chart/2018_HerbicideInjury_BRA.pdf) version.

• *UW Waterhemp Challenge: Preliminary Report Comparison of Soil Residual Herbicides* \hfill Ago  2018  
[Link](http://www.wiscweeds.info/img/2018%20waterhemp%20challenge/Waterhemp%20Management%20PRE%20Comparison_Lancaster%20WI%202018.pdf)

# PROGRAMAÇÃO

• [R](https://www.r-project.org) e [Rstudio](https://www.rstudio.com)

• [GitHub](https://github.com)

• [LaTeX](https://latex.org) e [Markdown](https://www.markdownguide.org)

• Agricultural Research Management [(ARM)](https://www.arm.com/products/development-tools)

• Statistical Analysis Software [(SAS)](https://www.sas.com/)

# PROJETOS PESSOAIS

• Open Source Weed Science – Um repositório com tutoriais de análise e visualização de dados publicados em artigos de planta daninha e áreas relacionadas

• Blog: https://maxweeds.rbind.io - Meu blog pessoal

# LINGUAS

• Português (Nativo)

• Inglês (Bilingual)

• Espanhol (Intermediário) 