---
title: "Cover letter"
author: ""
date: ""
output: pdf_document

header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO,CE]{Cover letter}
- \fancyfoot[CO,CE]{Cover letter - Maxwel Coura Oliveira}
- \fancyfoot[LE,RO]{\thepage}


fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(knitr)
```




\hfill Maxwel Coura Oliveira, Ph.D.

\hfill Postdoctoral Research Associate Weed Scientist

\hfill University of Wisconsin-Madison

August 06, 2019

University of Minnesota  
Department of Agronomy and Plant Genetics  
Saint Paul, MN  


Dear Dr. Roger Becker and search committee members,

\vspace{35pt}

Thank you for considering my interest in the Assistant Professor Integrated Cropping Systems Extension Weed Scientist (330561) in the Department of Agronomy and Plant Genetics, University of Minnesota. My educational background and research, extension, and teaching experiences in agriculture have prepared me for a successful career as an Assistant Professor of Weed Science. Moreover, the job description aligns with my current and future research and extension interests.
	
My early passion for Agriculture led me to join the Federal University of Jequitinhonha and Mucuri Valleys (UFVJM), in Brazil, for a Bachelor’s Degree program in Agronomy. During my undergraduate studies, I worked with forage and rangeland science, particularly looking at the use of forage grasses for phytoremediation of an urban solid deposit area. I had the chance to present my results at scientific meetings. Also, I published my first scientific paper as a co-author in the Brazilian Journal of Animal Science. Moreover, I had the opportunity to organize field days, expeditions, and seminars for students and growers. During my senior year, I had the great opportunity to come to the United States of America through The Ohio State University as a visiting intern student. As part of my senior internship, I worked on a trainee program in a vegetable farm in Commerce, Michigan, and a hydroponic tomato greenhouse in Brockport, New York. During the time in Michigan, I dealt extensively with pest control, including weed management, and realized that cropping-systems/weed science was the career path I wanted to follow in my professional life. Upon my return to Brazil, I became a teaching assistant of an Integrated Weed Management course at the UFVJM. At this time, I was also offered an assistantship at the UFVJM to start an MS program in Weed Science after my graduation. 

As an MS student, I researched in the area of weed competition and management. I studied the interference of weed species growing with corn and the efficacy of different glyphosate formulations on weed control. A manuscript from my MS research was published in the Weed Research journal. I was also involved in some extra projects, including the use of *Brachiaria brizantha* for phytoremediation of picloram herbicide in the soil. Additionally, I was part of a team that conducted a series of research studies with cassava production with local growers in the Jequitinhonha region of Minas Gerais, Brazil. As part of the project, we organized field days and seminars to disseminate our research findings to cassava growers. During my last semester as an MS student, I was hired to work with specialized fertilizer sales in the Amazonian region of Brazil. My role was sales management trainee in the French company TIMAC Agro. I was being prepared to manage a team of fertilizer sales. I worked closely with the company marketing, regional manager, and palm oil/corn/soybean growers. During that time, I quickly realized that research rather than sales was the path that I wanted to follow in my career. 

In 2013 I applied for a grant through the Brazilian Science Without Borders Program ($130,000) to support my Ph.D. at the University of Nebraska-Lincoln (UNL), which allowed me to start my Ph.D. program in 2014. As a doctoral student, I worked with Dr. Stevan Knezevic on an *Amaranthus tuberculatus* (waterhemp) population that had evolved resistance to 4-hydroxyphenylpyruvate dioxygenase (HPPD)-inhibitor herbicide in Nebraska. Specifically, we 1) quantified the levels of herbicide resistance and evaluated herbicide programs to provide effective control of this resistant population; 2) confirmed the mechanism in the HPPD-resistant waterhemp population; 3) investigated the inheritance of mesotrione (an HPPD-inhibitor) in the HPPD-resistant waterhemp population; and 4) studied pollen-mediated gene flow between HPPD-resistant waterhemp and HPPD-susceptible waterhemp and to HPPD-susceptible Palmer amaranth (*Amaranthus palmeri*) population. In my Ph.D. projects, I work closely with Dr. Todd Gaines and Dr. Franck Dayan from Colorado State University. I had the chance to visit Colorado State University twice during my program to conduct some of my lab work. The four chapters of my dissertation are already published in prestigious peer-review journals (i.e., Weed Technology, Pest Management Science, Frontiers in Plant Science, and the Plant Journal).

Thus far I have published (author and co-author) twenty three manuscripts in peer-reviewed journals, and three are in preparation. I have presented over 35 abstracts and received two poster presentation awards at scientific meetings. These indicate my ability to write and communicate in formal and also applied/practical settings. To accomplish my research objectives during my training, I collaborated and closely worked with scientists outside my discipline (e.g., plant pathology, molecular biology, genetics, and biochemistry, etc.), allowing me to understand the importance of multi-disciplinary teamwork. During my time in Nebraska, I worked on several other projects with my colleagues. For example, I had the chance to visit the University of Illinois Urbana-Champaign to work on PPO herbicide resistance Palmer amaranth in Dr. Tranel’s lab. I also assisted my adviser in Nebraska with his program’s herbicide efficacy trials and other weed research projects. Some of the research projects included critical time for weed removal, flaming for weed control (organic systems), micro-rates of dicamba on sensitive soybeans and vegetables, herbicide weed control in cropping-systems, pastures, rangeland, and wet areas. As a graduate student, I also had the opportunity to teach the laboratory section of Invasive Plants in 2016/17 with Dr. John Lindquist. As part of the lab, I thought weed and herbicide ID, herbicide calibration, weed resistance management. Teaching this class was an excellent opportunity to train and interact with the next generation of decision makers.

During my time in Nebraska, I dedicated part of my time to work on statistical data analysis. I was responsible for analyzing not only my data but the research data from Knezevic’s weed science program. I started using R and R-studio in 2014, and now I feel proficient using the software for data analysis. I was able to help my fellow graduate student colleagues on their data analysis, including students from plant pathology and entomology. My programming skill with R leads me to develop my academic blog (https://maxweeds.rbind.io/) using R-studio and GitHub. My blog will serve as a tool to publish part of my project (Open Source Weed Science), which aims to share R codes for data analysis and data visualization commonly used in weed and agricultural research. I believe that handling and understanding data is essential to comprehend the big picture, which allows guiding the future needs of a research program. Also, data analysis and data visualization are crucial for communicating research results to the public. 

In January 2018, I joined Dr. Rodrigo Werle’s lab at the University of Wisconsin-Madison as a Postdoctoral Research Associate in Weed Science. In my current position, my objective is to assist the Werle’s lab to conduct innovative and collaborative research and extension programming to increase profitability, productivity, and sustainability of corn, soybean, and small grains in Wisconsin. As part of my role, I am mentoring graduate students and training the Badger Weeds Team, which took 2^nd^ place in the 2018 North Central Weed Science Weeds Contest. I oversee the graduate student' projects, and I was responsible for three projects, including investigating the PPO and glyphosate resistance in Palmer amaranth, the ecological adaptation of Palmer amaranth to the upper Midwest and off-target movement of dicamba in multiple states. Also, I am aiding a multidisciplinary team to implement of several industrial help projects. I am currently working on research grants, which will allow me to recruit and train new graduate students in our program. Meanwhile, I am developing my skills to become better qualified to obtain an Assistant Professor of Weed Science position.

I’m excited to work with cropping systems and to continue an internationally recognized research and extension program focused on the development of integrated weed management strategies for specialty crops widely grown in the state of Minnesota. I would be ready to cooperate with the diverse and talented group of scientists located at the Department of Agronomy and Plant Genetics. I am confident this position will help me achieve my professional goals and believe that my previous experiences and future goals are a secure fit for the job. My philosophy will be the multidisciplinary work in conciliation of Research-Teaching-Extension to address pressing and future issues, and to better prepare farmers (today’s decision makers) and students (tomorrow’s decision makers) for tomorrow’s challenging global agriculture. Thank you for your consideration, and I hope to further discuss this opportunity with you shortly. 


Sincerely,


\vspace{70pt}



\begin{center}
Maxwel Coura Oliveira 
\end{center}
