---
title: "Statement of diversity, equity and inclusion"
author: | 
  | Maxwel Coura Oliveira, Ph.D
  | Postdoctoral Research Associate, University of Wisconsin-Madison
  
date: ""

header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO,CE]{References}
- \fancyfoot[CO,CE]{References - Maxwel Coura Oliveira}
- \fancyfoot[LE,RO]{\thepage}

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue

output: pdf_document
---



As a Brazilian (e.g., Latin American), I recognize the barriers that minorities face in everyday life, especially in STEM fields. Over the years, I have encouraged diversity and inclusive environment in my workplace by interacting with colleagues from different ethnicities, races, education levels, and sexual orientations. During my time in Brazil, Nebraska and Wisconsin, I have mentored North American, Brazilian, Serbian, and Peruvian from different backgrounds, including exchange visitor, high school, undergraduate, and graduate students. For example, I have mentored an economically disadvantaged high school student in Brazil, which graduated from college and is now a graduate student. Mentoring was a particularly rewarding experience as the student has become the first generation college student in her family.

Currently, at UW-Madison, I am supervising two undergraduate research scholars (URS), including Peruvian and Chinese-American students. This program designed to introduce minority students (sophomore or freshman) to science. The undergraduate students are leading their research project and having the opportunity to interact with graduate students, postdocs, and professors. One of the undergraduate students attended the 2018 North Central Weed Science Meeting and presented a poster. The undergraduate students are excited about their program, and they are currently interested in graduate school.

As a University of Minnesota faculty member, I am eager to promote Minnesota's values of diversity, equity, and inclusion in my Integrated Cropping Systems Extension Weed Science program by choosing to work with and hire staff and students from a range of backgrounds and help them develop their scientific skills towards their career goals. I will help students from underrepresented groups transition to college or graduate school, as this is a particularly difficult period of their lives, and help them throughout their school programs. I want to make an inclusive environment in my workplace. I would provide research opportunities for everyone, especially students historically excluded from the weed science discipline based on their background. Advising and mentoring, in my opinion, are critical strategies to inclusivity, and I will advocate these actions in my weed science program and as a faculty member at University of Minnesota. 

\newpage

Sincerely, 

\vspace{80pt}

\begin{center}
Maxwel Coura Oliveira 
\end{center}
