---
title: CV
format:
  quarto-cv-pdf: default
author: Maxwel C Oliveira
date: last-modified
phone: +49 1520-5854-941
address: "Krohst 2 · Cologne 50968, GE"
email: maxwelco@tuta.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
#github: github # github account
#orcid: 0000-0002-1825-0097 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
web: quarto.org
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
  other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Employment


*Senior Digital Agronomist* - **BASF Digital Farming GmbH**, Cologne, Germany \hfill Oct 2023-Current

 -- Coordinating smart spraying research and development with xarvio for the One Smart Spray platform in the US.  
 -- Development and maintaining strong relationships with stakeholders.   
 -- Development of agronomic digital intelligence for xarvio Field Manager.  

*Assistant Professor* - **McGill University**, Saint-Anne-de-Bellevue, Canada \hfill Jan 2023-Sep 2023

 -- Tenure-track Assistant Professor of Weed Science.  
 
*Research and Training Coordinator* - **Teejet Technologies**, São Paulo, Brazil \hfill Nov 2021-Sep 2022

 -- Tenure-track Assistant Professor of Weed Science.  


# Education

*New College, Oxford University*, B.A. Chemistry \hfill 1899

# Publications

::: {#refs-peer}
:::

# Technical Reports

::: {#refs-other}
:::


# References

Available upon request, though likely would include Karl Pearson and Ronald A. Fisher.
